export const TIPS: readonly string[] = [
  'Use /screen to snap your display and attach it to the chat for visual context',
  'Highlight text in any app before summoning Thuki to include it as context',
  '/think makes Thuki reason step by step before answering, great for hard questions',
  '/search pulls live web results into the chat so answers stay current',
  '⌘W or Esc hides the window; Thuki keeps running in the background',
  'Drop an image onto the bar to attach it and ask questions about what you see',
  'Paste images from your clipboard directly; no need to save to disk first',
  'Click the chip icon to switch between any model you have installed in Ollama',
  'The bookmark icon saves the full conversation so you can come back to it later',
  '/translate converts your selected text to any language you specify',
  'Click the clock icon to browse all your past conversations',
  'Highlight any text and type /rewrite to get a cleaner, better-flowing version without changing the meaning',
  '/tldr condenses any highlighted or pasted block of text into 1-3 sentences',
  '/refine fixes grammar, spelling, and punctuation in highlighted text while keeping your voice and tone',
  '/bullets turns highlighted text or a pasted block into a concise bullet list of key points',
  '/todos scans highlighted text or notes and pulls out every action item as a checkbox list',
  'Type / in the ask bar to see all available commands and pick one with Tab',
  'Commands can combine in one message: try /screen /think to capture your screen and reason through it',
  'Everything runs locally through Ollama; your conversations never leave your machine',
  'Attach images to your messages for visual context; visit Settings to adjust the limit',
  'Turn on Keep Warm in Settings to skip the active model load time — your first reply is instant every time',
  'Keep Warm holds your active model ready in VRAM so there is no loading delay when you summon Thuki',
  'Set a release timer in Settings to keep your active model warm for a while, then free VRAM automatically',
  'Keep Warm auto-releases after your chosen timeout so it never holds GPU memory longer than you need',
  'The green dot next to your active model in Settings means it is live in VRAM and ready to respond instantly',
  'Keep Warm in Settings keeps your active model loaded between sessions so Thuki is always ready at full speed',
];
