// Refreshes the autogenerated regions of src-tauri/src/websearch/credibility_domains.txt
// from upstream license-clean ad/SEO-spam-blocklist sources. Run manually with
// `bun scripts/refresh-credibility-list.ts` or via the scheduled
// credibility-list-refresh GitHub Action (see .github/workflows/credibility-list-refresh.yml).
//
// Only text between "# BEGIN AUTOGEN <source-id>" / "# END AUTOGEN <source-id>"
// sentinel comments is rewritten; every other byte in the file (the drop section,
// the boost section, and the hand-curated penalize clusters) is left untouched.
// This mirrors the existing Renovate engine-bump pattern (#238): automation
// proposes a diff, a human reviews and merges it. The app itself never fetches
// these lists at runtime; this script is dev/CI tooling only.

import { promises as dns } from 'node:dns';
import { mkdtemp, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/** Byte cap on any single fetched upstream response, a guard against a hung or hostile server. */
const MAX_RESPONSE_BYTES = 5 * 1024 * 1024;

/** Minimum domains a parsed region must yield; fewer trips the truncation/hijack guard. */
const MIN_REGION_DOMAINS = 10;

/** Domain count above which a region is flagged in the summary as suspiciously large. */
const WARN_REGION_MAX_DOMAINS = 5000;

/** DNS lookup timeout for the drop-section liveness check, per domain. */
const DNS_TIMEOUT_MS = 4000;

const repoRoot = fileURLToPath(new URL('../', import.meta.url));
const CREDIBILITY_FILE = resolve(
  repoRoot,
  'src-tauri/src/websearch/credibility_domains.txt',
);

/** The two upstream line formats an autogen source can be published in. */
type SourceFormat = 'ublacklist' | 'domain-list';

/** One upstream source feeding a single autogen sentinel region. */
interface Source {
  /** Sentinel id, must match "# BEGIN/END AUTOGEN <id>" in the txt file. */
  id: string;
  /** Raw-content URL fetched over HTTPS. */
  url: string;
  /** Line format the fetched text is in. */
  format: SourceFormat;
  /** One-line courtesy credit written at the top of the rewritten region. */
  credit: string;
}

const SOURCES: readonly Source[] = [
  {
    id: 'quenhus-seo-spam',
    url: 'https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/dist/other_format/domains/seo_spam.txt',
    format: 'domain-list',
    credit:
      '# source: quenhus/uBlock-Origin-dev-filter (dist/other_format/domains/seo_spam.txt), Unlicense',
  },
  {
    id: 'quenhus-wikipedia-copycats',
    url: 'https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/dist/other_format/domains/wikipedia_copycats.txt',
    format: 'domain-list',
    credit:
      '# source: quenhus/uBlock-Origin-dev-filter (dist/other_format/domains/wikipedia_copycats.txt), Unlicense',
  },
  {
    id: 'arosh-stackoverflow-copycats',
    url: 'https://raw.githubusercontent.com/arosh/ublacklist-stackoverflow-translation/master/uBlacklist.txt',
    format: 'ublacklist',
    credit:
      '# source: arosh/ublacklist-stackoverflow-translation (uBlacklist.txt), CC0-1.0',
  },
];

/** Verdict for one drop-list domain's liveness probe. */
type LivenessVerdict = 'resolves' | 'possibly dead' | 'inconclusive';

/**
 * Fetches `url` over HTTPS as text, aborting if the response body exceeds
 * `maxBytes`. Streams the body rather than trusting a Content-Length header,
 * since that header can be absent or wrong. Throws on a non-2xx status, a
 * missing body, or the size cap being exceeded.
 */
async function fetchWithCap(url: string, maxBytes: number): Promise<string> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`fetch ${url} failed: HTTP ${response.status}`);
  }
  const body = response.body;
  if (!body) {
    throw new Error(`fetch ${url} returned no response body`);
  }
  const reader = body.getReader();
  const chunks: Uint8Array[] = [];
  let total = 0;
  for (;;) {
    const { done, value } = await reader.read();
    if (done) {
      break;
    }
    total += value.byteLength;
    if (total > maxBytes) {
      await reader.cancel();
      throw new Error(
        `fetch ${url} exceeded ${maxBytes} byte cap (truncated read at ${total} bytes)`,
      );
    }
    chunks.push(value);
  }
  const buffer = Buffer.concat(chunks.map((c) => Buffer.from(c)));
  return buffer.toString('utf8');
}

/**
 * Validates and normalizes one extracted domain token. Lowercases the token,
 * strips any character outside `[a-z0-9.-]` (defense against comment injection
 * or control characters riding in on a hijacked upstream file), drops a
 * leading `www.` label (the file's own header contract is "no scheme or
 * www"; a `www.`-only entry would not cover the bare domain via the parser's
 * host-to-parent suffix walk, silently weakening coverage), then requires the
 * result to look like a registrable domain: at least two dot-separated
 * labels, each label alphanumeric-with-internal-hyphens only. Only the
 * cosmetic `www.` prefix is stripped, not reduced to eTLD+1 in general: the
 * list intentionally carries meaningful subdomains (e.g.
 * `agecalculator.iamrohit.in`), which a general collapse would over-widen.
 * Returns null for anything that fails the shape check, so the caller can
 * drop it silently.
 */
function normalizeDomainToken(raw: string): string | null {
  const lowered = raw.toLowerCase();
  const stripped = lowered.replace(/[^a-z0-9.-]/g, '');
  const withoutWww = stripped.replace(/^www\./, '');
  const labels = withoutWww.split('.');
  if (labels.length < 2) {
    return null;
  }
  const labelPattern = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/;
  if (!labels.every((label) => label.length > 0 && labelPattern.test(label))) {
    return null;
  }
  return withoutWww;
}

/**
 * Parses the arosh uBlacklist match-pattern format: lines like
 * `*://code-examples.net/*` or a wildcard-subdomain form `*://*.voidcc.com/*`.
 * Strips the `*://` scheme prefix, an optional leading `*.` wildcard label,
 * and everything from the first `/` onward (path-scoped entries collapse to
 * their host), then normalizes what remains as a domain token.
 */
function parseUblacklistFormat(text: string): string[] {
  const domains: string[] = [];
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (line.length === 0 || line.startsWith('#')) {
      continue;
    }
    const withoutScheme = line.replace(/^\*:\/\//, '');
    const withoutWildcardSubdomain = withoutScheme.replace(/^\*\./, '');
    const host = withoutWildcardSubdomain.split('/')[0] ?? '';
    const normalized = normalizeDomainToken(host);
    if (normalized) {
      domains.push(normalized);
    }
  }
  return domains;
}

/**
 * Parses the quenhus `dist/other_format/domains/*.txt` format: `#`-prefixed
 * comments and blank lines are skipped, and each remaining line is a bare
 * domain, optionally followed by a path (`brianlovin.com/hn`), which is
 * dropped by keeping only the portion before the first `/`.
 */
function parseDomainListFormat(text: string): string[] {
  const domains: string[] = [];
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (line.length === 0 || line.startsWith('#')) {
      continue;
    }
    const host = line.split('/')[0] ?? '';
    const normalized = normalizeDomainToken(host);
    if (normalized) {
      domains.push(normalized);
    }
  }
  return domains;
}

/** Parses `text` per `format` into a raw (unsorted, possibly duplicated) domain list. */
function parseSource(text: string, format: SourceFormat): string[] {
  return format === 'ublacklist'
    ? parseUblacklistFormat(text)
    : parseDomainListFormat(text);
}

/** Lowercases, deduplicates, and lexicographically sorts a domain list for deterministic output. */
function dedupeSort(domains: readonly string[]): string[] {
  return Array.from(new Set(domains.map((d) => d.toLowerCase()))).sort();
}

/** One sentinel-delimited region located inside the credibility txt file. */
interface Region {
  /** Line index of the "# BEGIN AUTOGEN <id>" marker. */
  beginIndex: number;
  /** Line index of the "# END AUTOGEN <id>" marker. */
  endIndex: number;
  /** Domain lines currently between the markers (excludes credit comment lines). */
  domains: string[];
}

/**
 * Locates the sentinel region for `sourceId` inside `lines` (the credibility
 * file split on newlines). Returns the marker line indices plus the domain
 * lines currently inside the region (any line starting with `#` between the
 * markers is a courtesy-credit comment, not a domain, and is excluded).
 * Throws if the markers are missing or malformed, since a missing sentinel
 * means the file was hand-edited out of sync with this script's expectations.
 */
function findRegion(lines: readonly string[], sourceId: string): Region {
  const beginMarker = `# BEGIN AUTOGEN ${sourceId}`;
  const endMarker = `# END AUTOGEN ${sourceId}`;
  const beginIndex = lines.indexOf(beginMarker);
  const endIndex = lines.indexOf(endMarker);
  if (beginIndex === -1 || endIndex === -1 || endIndex < beginIndex) {
    throw new Error(
      `could not locate sentinel region for "${sourceId}" (expected "${beginMarker}" / "${endMarker}")`,
    );
  }
  const domains = lines
    .slice(beginIndex + 1, endIndex)
    .map((l) => l.trim())
    .filter((l) => l.length > 0 && !l.startsWith('#'));
  return { beginIndex, endIndex, domains };
}

/**
 * Rewrites the sentinel region for `source` inside `lines`, replacing
 * everything between its BEGIN/END markers with the courtesy credit line
 * followed by the sorted `domains`. The markers themselves, and every line
 * outside them, are left untouched. Returns a new line array.
 */
function replaceRegion(
  lines: readonly string[],
  source: Source,
  domains: readonly string[],
): string[] {
  const { beginIndex, endIndex } = findRegion(lines, source.id);
  const replacement = [source.credit, ...domains];
  return [
    ...lines.slice(0, beginIndex + 1),
    ...replacement,
    ...lines.slice(endIndex),
  ];
}

/**
 * Parses the credibility file's `# drop` section into a domain list, mirroring
 * the section-header handling in src-tauri/src/websearch/credibility.rs: a
 * line reading exactly `# drop`, `# penalize`, or `# boost` switches section;
 * any other `#` line (including a BEGIN/END sentinel) is a comment; a blank
 * line is skipped; anything else inside the `# drop` section is a domain.
 */
function extractDropSection(fileText: string): string[] {
  const domains: string[] = [];
  let inDrop = false;
  for (const rawLine of fileText.split('\n')) {
    const line = rawLine.trim();
    if (line.length === 0) {
      continue;
    }
    if (line.startsWith('#')) {
      const header = line.slice(1).trim();
      if (header === 'drop' || header === 'penalize' || header === 'boost') {
        inDrop = header === 'drop';
      }
      continue;
    }
    if (inDrop) {
      domains.push(line.toLowerCase());
    }
  }
  return domains;
}

/**
 * Resolves `domain` with a bounded timeout to classify it as still live,
 * possibly dead, or inconclusive. A successful lookup is "resolves"; an
 * ENOTFOUND/ENODATA error (the DNS server affirmatively has no record) is
 * "possibly dead"; anything else (timeout, network failure, other resolver
 * errors) is "inconclusive" because it does not prove the domain is gone.
 */
async function checkLiveness(domain: string): Promise<LivenessVerdict> {
  let timeoutHandle: ReturnType<typeof setTimeout> | undefined;
  const timeout = new Promise<'timeout'>((resolve) => {
    timeoutHandle = setTimeout(() => resolve('timeout'), DNS_TIMEOUT_MS);
  });
  try {
    // Held separately from the race so a late rejection (arriving after the
    // timeout branch has already won) still has a handler attached and does
    // not surface as an unhandledRejection once main() has moved on.
    const lookup = dns.lookup(domain);
    lookup.catch(() => {});
    const outcome = await Promise.race([
      lookup.then(() => 'resolved' as const),
      timeout,
    ]);
    if (outcome === 'timeout') {
      return 'inconclusive';
    }
    return 'resolves';
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    if (code === 'ENOTFOUND' || code === 'ENODATA') {
      return 'possibly dead';
    }
    return 'inconclusive';
  } finally {
    clearTimeout(timeoutHandle);
  }
}

/** One row of the drop-list liveness report. */
interface LivenessResult {
  domain: string;
  verdict: LivenessVerdict;
}

/** Runs `checkLiveness` over every drop-section domain, in parallel. */
async function checkDropListLiveness(
  domains: readonly string[],
): Promise<LivenessResult[]> {
  return Promise.all(
    domains.map(async (domain) => ({
      domain,
      verdict: await checkLiveness(domain),
    })),
  );
}

/** Writes `content` to `path` atomically: write to a sibling temp file, then rename over the target. */
async function writeFileAtomic(path: string, content: string): Promise<void> {
  const tmpDir = await mkdtemp(join(dirname(path), '.refresh-tmp-'));
  const tmpPath = join(tmpDir, 'credibility_domains.txt');
  try {
    await writeFile(tmpPath, content, 'utf8');
    await rename(tmpPath, path);
  } finally {
    await rm(tmpDir, { recursive: true, force: true });
  }
}

/** Per-region before/after domain counts and set diff, for the summary. */
interface RegionReport {
  sourceId: string;
  previousCount: number;
  newCount: number;
  added: string[];
  removed: string[];
  warnings: string[];
}

/** Diffs `previous` against `next`, returning domains only in one side. */
function diffDomains(
  previous: readonly string[],
  next: readonly string[],
): { added: string[]; removed: string[] } {
  const previousSet = new Set(previous);
  const nextSet = new Set(next);
  return {
    added: next.filter((d) => !previousSet.has(d)).sort(),
    removed: previous.filter((d) => !nextSet.has(d)).sort(),
  };
}

/**
 * Renders the markdown maintenance summary: per-section counts (drop /
 * penalize / boost), per-region before/after counts with added/removed
 * domains, any size-anomaly warnings, and the drop-list liveness report.
 */
function renderSummary(
  sectionCounts: { drop: number; penalize: number; boost: number },
  regionReports: readonly RegionReport[],
  liveness: readonly LivenessResult[],
): string {
  const lines: string[] = [];
  lines.push('# Credibility list refresh summary');
  lines.push('');
  lines.push('## Section counts');
  lines.push(`- drop: ${sectionCounts.drop}`);
  lines.push(`- penalize: ${sectionCounts.penalize}`);
  lines.push(`- boost: ${sectionCounts.boost}`);
  lines.push('');
  lines.push('## Autogen regions');
  for (const report of regionReports) {
    lines.push(`### ${report.sourceId}`);
    lines.push(
      `- domains: ${report.previousCount} -> ${report.newCount} (added ${report.added.length}, removed ${report.removed.length})`,
    );
    for (const warning of report.warnings) {
      lines.push(`- warning: ${warning}`);
    }
    if (report.added.length > 0) {
      lines.push('<details><summary>Added domains</summary>');
      lines.push('');
      lines.push(report.added.map((d) => `- ${d}`).join('\n'));
      lines.push('');
      lines.push('</details>');
    }
    if (report.removed.length > 0) {
      lines.push('<details><summary>Removed domains</summary>');
      lines.push('');
      lines.push(report.removed.map((d) => `- ${d}`).join('\n'));
      lines.push('');
      lines.push('</details>');
    }
    lines.push('');
  }
  lines.push('## Drop-list liveness (report only, list never modified)');
  const possiblyDead = liveness.filter((r) => r.verdict === 'possibly dead');
  const inconclusive = liveness.filter((r) => r.verdict === 'inconclusive');
  lines.push(
    `- ${liveness.length} domains checked: ${liveness.length - possiblyDead.length - inconclusive.length} resolve, ${possiblyDead.length} possibly dead, ${inconclusive.length} inconclusive`,
  );
  if (possiblyDead.length > 0) {
    lines.push(
      '- possibly dead: ' + possiblyDead.map((r) => r.domain).join(', '),
    );
  }
  if (inconclusive.length > 0) {
    lines.push(
      '- inconclusive: ' + inconclusive.map((r) => r.domain).join(', '),
    );
  }
  lines.push('');
  return lines.join('\n');
}

/** Reads `--summary <path>` from argv, if present. */
function parseArgs(argv: readonly string[]): { summaryPath: string | null } {
  const idx = argv.indexOf('--summary');
  if (idx === -1 || idx + 1 >= argv.length) {
    return { summaryPath: null };
  }
  return { summaryPath: argv[idx + 1] ?? null };
}

/**
 * Entry point: fetches every upstream source, parses and validates it,
 * rewrites only the matching sentinel regions of the credibility file, runs
 * the drop-list liveness check, and writes the markdown summary (to stdout
 * always, and to `--summary <path>` if given). Exits nonzero without touching
 * the credibility file if any region parses to fewer than MIN_REGION_DOMAINS
 * domains, since that indicates upstream truncation or hijack.
 */
async function main(): Promise<void> {
  const { summaryPath } = parseArgs(process.argv.slice(2));
  const originalText = await readFile(CREDIBILITY_FILE, 'utf8');
  const originalLines = originalText.split('\n');

  const regionReports: RegionReport[] = [];
  let updatedLines = originalLines;

  for (const source of SOURCES) {
    const previousRegion = findRegion(originalLines, source.id);
    const fetched = await fetchWithCap(source.url, MAX_RESPONSE_BYTES);
    const parsed = parseSource(fetched, source.format);
    const domains = dedupeSort(parsed);
    if (domains.length < MIN_REGION_DOMAINS) {
      throw new Error(
        `source "${source.id}" parsed to only ${domains.length} domains (minimum ${MIN_REGION_DOMAINS}); ` +
          'refusing to write, this looks like upstream truncation or a hijacked response',
      );
    }
    const warnings: string[] = [];
    if (domains.length > WARN_REGION_MAX_DOMAINS) {
      warnings.push(
        `region has ${domains.length} domains, above the ${WARN_REGION_MAX_DOMAINS} sanity threshold`,
      );
    }
    if (
      previousRegion.domains.length > 0 &&
      domains.length < previousRegion.domains.length / 2
    ) {
      warnings.push(
        `region shrank from ${previousRegion.domains.length} to ${domains.length} domains (more than half)`,
      );
    }
    const { added, removed } = diffDomains(previousRegion.domains, domains);
    regionReports.push({
      sourceId: source.id,
      previousCount: previousRegion.domains.length,
      newCount: domains.length,
      added,
      removed,
      warnings,
    });
    updatedLines = replaceRegion(updatedLines, source, domains);
  }

  const updatedText = updatedLines.join('\n');
  const dropDomains = extractDropSection(updatedText);
  const penalizeSectionCount = countSectionDomains(updatedText, 'penalize');
  const boostSectionCount = countSectionDomains(updatedText, 'boost');

  const liveness = await checkDropListLiveness(dropDomains);

  const summary = renderSummary(
    {
      drop: dropDomains.length,
      penalize: penalizeSectionCount,
      boost: boostSectionCount,
    },
    regionReports,
    liveness,
  );

  await writeFileAtomic(CREDIBILITY_FILE, updatedText);

  process.stdout.write(summary + '\n');
  if (summaryPath) {
    await writeFile(resolve(summaryPath), summary, 'utf8');
  }
}

/**
 * Counts domains in a named section (`drop` / `penalize` / `boost`), the same
 * way `extractDropSection` does for `drop`, generalized to any of the three.
 */
function countSectionDomains(fileText: string, section: string): number {
  let count = 0;
  let inSection = false;
  for (const rawLine of fileText.split('\n')) {
    const line = rawLine.trim();
    if (line.length === 0) {
      continue;
    }
    if (line.startsWith('#')) {
      const header = line.slice(1).trim();
      if (header === 'drop' || header === 'penalize' || header === 'boost') {
        inSection = header === section;
      }
      continue;
    }
    if (inSection) {
      count += 1;
    }
  }
  return count;
}

main().catch(async (err) => {
  const message = err instanceof Error ? err.message : String(err);
  process.stderr.write(`refresh-credibility-list: ${message}\n`);
  const { summaryPath } = parseArgs(process.argv.slice(2));
  const failureSummary = `# Credibility list refresh summary\n\nRefresh failed, credibility_domains.txt was not modified:\n\n\`\`\`\n${message}\n\`\`\`\n`;
  process.stdout.write(failureSummary);
  if (summaryPath) {
    await writeFile(resolve(summaryPath), failureSummary, 'utf8').catch(
      () => undefined,
    );
  }
  process.exitCode = 1;
});
